on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        name: [
          debug-bitwuzla,
          debug-boolector,
          debug-cvc5,
          debug-yices,
        ]

        include:
          - name: debug-bitwuzla
            config: -DDOCS=off -DENABLE_BITWUZLA=on -DENABLE_BOOLECTOR=off -DENABLE_CVC5=off -DENABLE_YICES=off
            depconfig: --only-bzla

          - name: debug-boolector
            config: -DDOCS=off -DENABLE_BITWUZLA=off -DENABLE_BOOLECTOR=on -DENABLE_CVC5=off -DENABLE_YICES=off
            depconfig: --only-btor

          - name: debug-cvc5
            config: -DDOCS=off -DENABLE_BITWUZLA=off -DENABLE_BOOLECTOR=off -DENABLE_CVC5=on -DENABLE_YICES=off
            depconfig: --only-cvc5

          - name: debug-yices
            config: -DDOCS=off -DENABLE_BITWUZLA=off -DENABLE_BOOLECTOR=off -DENABLE_CVC5=off -DENABLE_YICES=on
            depconfig: --only-yices

    name: ${{ matrix.os }}:${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install gperf
          python3 -m pip install toml

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Dependencies
        if: steps.restore-deps.outputs.cache-hit != 'true'
        run: |
          ./scripts/setup-solvers.sh ${{ matrix.depconfig }}

      - name: Configure
        run: |
          mkdir build
          cd build
          ${{ matrix.env }} cmake .. ${{ matrix.config }}

      - name: Build
        run: make -j2
        working-directory: build
